👷 Test functions, don't publish packages with failed tests
Signed-off-by: Daniel Ruthardt <druthardt@linuxfoundation.org>

diff --git a/.github/workflows/package.yaml b/.github/workflows/package.yaml
--- a/.github/workflows/package.yaml
+++ b/.github/workflows/package.yaml
@@ -10,51 +10,18 @@ on:
   workflow_call:
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
-    needs: [setup]
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Create temporary Dockerfile
-        run: |
-          cat >libs/Dockerfile <<'EOF'
-          FROM scratch
-          LABEL org.opencontainers.image.source https://github.com/${{ github.repository }}
-          
-          ARG PACKAGE
-          ADD ${PACKAGE} /${PACKAGE}/
-          EOF
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: ./libs
-          file: ./libs/Dockerfile
-          build-args: PACKAGE=${{ matrix.item }}
-          push: true
-          tags: ghcr.io/lf-certification/bashp-${{ matrix.item }}:latest
-
   setup:
     runs-on: ubuntu-latest
     outputs:
-      matrix: ${{ steps.set-matrix.outputs.matrix }}
+      packages: ${{ steps.packages.outputs.matrix }}
+      functions: ${{ steps.functions.outputs.matrix }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: List all directories in libs and create matrix
-        id: set-matrix
+      - name: Get all packages
+        id: packages
+        shell: bash
         run: |
           json=$(
             (
@@ -64,6 +31,126 @@ jobs:
               echo '""'
             ) | sed -E 's/,?""$//'
           )
+          echo "matrix={\"package\":[$json]}" >> $GITHUB_OUTPUT
 
-          echo "matrix={\"item\":[$json]}" >> $GITHUB_OUTPUT
+      - name: Get all functions
+        id: functions
         shell: bash
+        run: |
+          json=$(
+            (
+              for directory in $(find libs/ -mindepth 1 -maxdepth 1 -type d); do
+                package="${directory#*/}"
+
+                for file in $(find "libs/$package" -type f -and \
+                                              ! -name '\*' -and \
+                                              ! -wholename '*/tests/*'); do
+                  directory=$(dirname "$file")
+                  fileName=$(basename "$file")
+                  if [[ ! -d "$directory/tests/$fileName" || ! -f "$directory/tests/$fileName/test" ]]; then
+                    continue
+                  fi
+
+                  functionName=${file#libs/*}
+                  functionName=${functionName//\//::}
+
+                  echo -n '{"package":"'"$package"'","function":"'"$functionName"'"},'
+                done
+              done
+              echo '""'
+            ) | sed -E 's/,?""$//'
+          )
+
+          echo "matrix={\"function\":[$json]}" >> $GITHUB_OUTPUT
+
+  test:
+    runs-on: ubuntu-latest
+    outputs:
+      results: ${{ toJson(steps.test.outputs) }}
+    needs: [setup]
+    if: needs.setup.outputs.functions != '{"include":[]}'
+    strategy:
+      matrix: ${{ fromJson(needs.setup.outputs.functions) }}
+      fail-fast: false
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v3
+
+      - name: Test function
+        id: test
+        shell: bash
+        run: |
+          export PATH=".:$PATH"
+          export BASHP_INCLUDE_DIRS="libs"
+
+          set +e
+          output=$(bashpt "${{ matrix.function.function }}" 2>&1)
+          exitCcode=$?
+          echo "$output"
+
+          if [[ $exitCode -eq 0 ]]; then
+            echo "✅ Test passed for ${{ matrix.function }}"
+          elif [[ $exitCode -eq 127 ]]; then
+            echo "🔍 No test defined for ${{ matrix.function }} (acceptable)"
+          else
+            echo "❌ Test failed for ${{ matrix.function }} (exit code: $exitCode)"
+            echo "${{ matrix.function.package }}=false" >> $GITHUB_OUTPUT
+          fi
+
+  package:
+    runs-on: ubuntu-latest
+    needs: [setup, test]
+    if: always() && needs.setup.outputs.packages != '{"include":[]}'
+    strategy:
+      matrix: ${{ fromJson(needs.setup.outputs.packages) }}
+      fail-fast: false
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Check if all tests passed for this package
+        id: check
+        run: |
+          if ! jq -e '.${{ matrix.package }} == "false"' <<<'${{ needs.test.outputs.results }}'; then
+            echo "✅ All tests passed for package ${{ matrix.package }}"
+            echo "package=true" >> $GITHUB_OUTPUT
+          else
+            echo "❌ Some tests failed for package ${{ matrix.package }}"
+            echo "package=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Set up Docker
+        if: steps.check.outputs.package == 'true'
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to GitHub Container Registry
+        if: steps.check.outputs.package == 'true'
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create temporary Dockerfile
+        if: steps.check.outputs.package == 'true'
+        run: |
+          cat >libs/Dockerfile <<'EOF'
+          FROM scratch
+          LABEL org.opencontainers.image.source https://github.com/${{ github.repository }}
+
+          ARG PACKAGE
+          ADD ${PACKAGE} /${PACKAGE}/
+          EOF
+
+      - name: Build and push Docker image
+        if: steps.check.outputs.package == 'true'
+        uses: docker/build-push-action@v5
+        with:
+          context: ./libs
+          file: ./libs/Dockerfile
+          build-args: PACKAGE=${{ matrix.package }}
+          push: true
+          tags: ghcr.io/lf-certification/bashp-${{ matrix.package }}:latest
